# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_file', models.FileField(upload_to='wall_messages_files/')),
                ('message_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
